export interface Publication {
    title: string,
    type: string,
    description: string,
    date: string,
    link: string,
    moretype: string,
    more: string,
}

export const publications: Publication[] = [
    {
        title: "Neural population responses to taste and food in the parabrachial nucleus of the pons in the awake unrestrained rat using in vivo one-photon Ca2 + imaging",
        type: "Conference Presentation",
        description: "We used one-photon in vivo Ca2+ imaging to track the activity of a population of PbN cells as they licked tastants, smelled food and ate solid food.",
        date: "SFN, 2022",
        link: "public/pdf/SFN_FinalPoster.pdf",
        moretype: "Abstract",
        more: `Although brainstem responses to taste stimuli have been well-documented, the function
                of the taste system in natural feeding remains unexplored. Based on previous
                electrophysiological data, we tested the hypothesis that the taste system is strongly
                engaged while exploring food, its taste and smell, but becomes mostly disengaged
                when food is being consumed. Here, we used in vivo one-photon Ca2+ imaging of cells
                in the parabrachial nucleus of the pons (PbN) of awake, unrestrained rats as they (i)
                licked representatives of four basic taste qualities (0.1 M sucrose, 0.1 NaCl, 0.0167 M
                citric acid, 0.0001 M quinine) as well as artificial saliva (AS) presented alone or paired
                with either peanut or chocolate odor, and (ii) ate either chocolate or peanuts presented
                in ”wells”, i.e. recessed open boxes placed at the corners of the experimental chamber.
                In separate surgeries 3 wks apart, rats were prepared for Ca2+ imaging by infusion of
                GCamp7s and implantation of a 1 mm dia. GRIN lens above the PbN. When recovered,
                rats were water-deprived and a miniscope (Inscopix, Inc.) was mounted above the
                GRIN lens. For the 20 min lick session, rats were placed in a chamber with a lick spout
                for delivery of taste stimuli, AS, AS+peanut odor or AS+chocolate odor. Each taste trial
                consisted of 10 consecutive taste stimulus licks preceded and followed by 6 AS licks
                delivered on a VR5 schedule. For odor trials, AS was presented for 10 consecutive licks
                the first of which initiated a 3 s puff of an odorant delivered through a port next to the
                lick spout. Odorants were generated by flowing compressed air over either chopped
                salted dry roasted peanuts or chopped milk chocolate (35% cacao, 67% sugar). A 20
                min eating session followed the lick session immediately. Doors to the wells were
                removed and 3 gms of peanuts or chocolate were placed in separate wells, to which the
                rats had free access. A video camera linked to the recording apparatus (CinePlex,
                Plexon, Inc.) was used to record behavior in the experimental chamber. Results from 2
                rats thus far have shown that all taste and odor stimuli evoked spatially widespread
                responses (>30 cells/rat) with no gustotopic segregation apparent. When rats ate either
                peanuts or chocolate, however, the number of responsive cells was spatially restricted
                to a small cluster of cells (~7-10) located in the caudo-medial field. Cells in this cluster
                also responded to all tastants and odorants tested, while each individual taste or odor
                stimulus additionally evoked unique spatial patterns of response scattered across the
                field. These data suggest that, in the PbN, taste and odor are represented by a dense,
                distributed code, while food is represented by a sparse and spatially restricted code.

                Funded by NIDCD grant RO1-DC006914 to PMD.`
    },
    {
        title: "Long term in vivo one-photon Ca2+ imaging of taste-responsive cells in the parabrachial pons in the awake freely licking rat",
        type: "Conference Presentation",
        description: "We used one-photon in vivo Ca2+ imaging to track the activity of a single population of parabrachial neurons over months.",
        date: "July. 2022",
        link: "/public/pdf/SFN_FinalPoster.pdf",
        moretype: "Abstract",
        more: `The observation that cells at all levels of the taste pathway respond primarily to a
single taste quality is the basis of labeled line theory. However, multiple studies have
shown that only a subset of cells in each structure are narrowly tuned. Here, we used in
vivo one-photon Ca2+ imaging of taste-responsive cells in the parabrachial nucleus of
the pons (PbN) of awake, freely licking rats to verify and expand those findings. Rats
were prepared for Ca 2+ imaging by infusion of GCamp7s and a GRIN lens into the PbN.
When recovered, rats were water-deprived and a miniscope (Inscopix, Inc.) was
mounted above the GRIN lens on the rat’s head. Rats were then placed in a chamber
with a lick spout for delivery of taste stimuli (sucrose, NaCl, citric acid, quinine, MSG).
Each trial consisted of 5 consecutive taste stimulus licks preceded and followed by 6
artificial saliva licks delivered on a VR5 schedule. Between 7-16 cells per rat were
present across multiple sessions over 2-12 wks. Results showed that taste-responsive,
lick-responsive and anti-lick cells could be identified in the PbN. For all taste cells, the
best stimulus varied across sessions. Taste cells often responded to one stimulus
consistently across sessions, but that stimulus was not always their best stimulus. In
some taste cells, the breadth of tuning was relatively stable across sessions, but the
best stimulus varied. In other cells, the breadth of tuning waxed and waned methodically
across sessions. Thus, on a given day, there was a subset of cells that were narrowly
tuned to a single taste quality, but the identity of these cells was different across days.
We suggest that these data reflect long term changes in input from turnover of
receptors. Further, these data point to a combinatorial view of taste coding in the PbN.`
    },
    {
        title: "Sprague Dawley Rats Gaining Weight on a High Energy Diet Exhibit Damage to Taste Tissue Even after Return to a Healthy Diet",
        type: "Journal Article",
        description: "Collectively, this paper argues that DIO has lasting deleterious effects on the peripheral taste system, despite a change from a HED to a healthy diet, underscoring the idea that obesity rather than diet predicts damage to the taste system.",
        date: "Aug. 2021",
        link: "https://pubmed.ncbi.nlm.nih.gov/34578940/",
        moretype: "Abstract",
        more: `Many reports detail taste dysfunction in humans and animals with obesity. For example, mice consuming an obesogenic diet for a short period have fewer taste buds than their lean littermates. Further, rats with diet-induced obesity (DIO) show blunted electrophysiological responses to taste in the brainstem. Here, we studied the effects of high energy diet (HED)-induced peripheral taste damage in rats, and whether this deficiency could be reversed by returning to a regular chow diet. Separate groups of rats consumed a standard chow diet (Chow), a HED for 10 weeks followed by a return to chow (HED/chow), or a HED for 10 weeks followed by a restricted HED that was isocaloric with consumption by the HED/chow group (HED/isocal). Fungiform taste papilla (FP) and circumvallate taste bud abundance were quantified several months after HED groups switched diets. Results showed that both HED/chow and HED/isocal rats had significantly fewer FP and lower CV taste bud abundance than control rats fed only chow. Neutrophil infiltration into taste tissues was also quantified, but did not vary with treatment on this timeline. Finally, the number of cells undergoing programmed cell death, measured with caspase-3 staining, inversely correlated with taste bud counts, suggesting taste buds may be lost to apoptosis as a potential mechanism for the taste dysfunction observed in obesity. Collectively, these data show that DIO has lasting deleterious effects on the peripheral taste system, despite a change from a HED to a healthy diet, underscoring the idea that obesity rather than diet predicts damage to the taste system. `
    },
]